export const TARGET_QUERIES = [
  'Product Owner',
  'PO',
  'Product Manager',
  'PM',
  'Business Analyst',
  'BA',
  'Proxy Product Owner',
  'Proxy PO',
  'Chef de projet digital',
  'Consultant AMOA',
  'AMOA',
  'Consultant MOA',
  'MOA',
  'Conseiller funéraire',
  'Assistant funéraire',
  'Métiers funéraires',
]
